environment: "dummy"

zerotier_config:
  zerotier_network_id: "netid"
  zerotier_network_name: "asimplename"
  zerotier_api_accesstoken: "sometoken"
  zerotier_authorize_member: true
  zerotier_label_service: "zerotier"

image:
  repository: omrisiri/kubernetes-zerotier-bridge
  tag: latest
  pullPolicy: IfNotPresent

resources: 
  limits:
    cpu: 0.8
    memory: 512Mi
  requests:
    cpu: 0.1
    memory: 64Mi

persistentVolume:
  enabled: false
  # storageClass: "-"
  accessModes:
    - ReadWriteOnce
  annotations: {}
  mountPath: /var/lib/zerotier-one
  size: 1Gi
