apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name:         "zerotier-{{ .Values.environment }}-{{ .Release.Name }}"
  namespace:    {{ .Release.Namespace }}
  labels:
    network:    {{ .Values.zerotier_config.zerotier_network_name }}
    service:    {{ .Values.zerotier_config.zerotier_label_service }}
stringData:
  ZTAUTHTOKEN:  {{ .Values.zerotier_config.zerotier_api_accesstoken }}
